---
# Backup all or a single project, the project_export.sh is used of the official openshift repo
- name: "Check if project name was provided"
  set_fact:
    proj2back: "{{ project_name if project_name is defined else '' }}" 
    project_backup_folder: "{{ 'projects' if project_name is not defined else 'proj-'+project_name }}"
    arch_name: "{{ 'openshift-projects-full' if project_name is not defined else 'proj-'+project_name }}"
  register: proj2back

# be sure JQ is installed
- name: "install required package JQ (json processor)"
  yum:
    name: jq
    state: latest

# export all projects or a single project
- name: "Run OpenShift Project Export script for {{ proj2back }}"
  shell: '{{script_dest_path }}/prep_project_export.sh {{ today_dest_path }}/{{project_backup_folder}} {{ proj2back }}'

# create an archive
- name: "Create archive for OpenShift Project"
  archive:
    path: '{{ today_dest_path }}/{{project_backup_folder}}'
    dest: '{{ today_dest_path }}/{{arch_name}}-{{ansible_date_time.date}}.gz'
    format: gz

# check if the zip archive has been created
- name: "Check if {{ today_dest_path }}/{{arch_name}}-{{ansible_date_time.date}}.gz"
  stat:
    path: "{{ today_dest_path }}/{{arch_name}}-{{ansible_date_time.date}}.gz"
  register: proj_archive_ok

# remove unzipped folder if archive has been created
- name: "Remove unzipped folder {{ today_dest_path }}/{{project_backup_folder}}"
  file:
    state: absent
    path: "{{ today_dest_path }}/{{project_backup_folder}}"
  when: proj_archive_ok.stat.exists == true
