---
# default files for ocp-backup
backup_root: /backup
backup_host: 'nfs-host:volume ... if applicable'
# if True, the playbook will try to to mount the mountpoint
nfs: True

backup_dest_path: '{{ backup_root }}/{{ inventory_hostname }}/'
script_dest_path: '{{ backup_root }}/scripts'
today_dest_path: '{{ backup_root }}/{{ inventory_hostname }}/{{ansible_date_time.date}}'
