- name: make actual node unschedulable
  command: oc adm manage-node {{ ansible_fqdn }} --schedulable=false --kubeconfig=/etc/origin/master/admin.kubeconfig
  delegate_to: "{{ groups.masters | first }}"


